---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alfio-cnpg-secret
  namespace: cnd-ticketing-2027
spec:
  encryptedData:
    password: AgAGrzxJfGV/+Vlti6TT1CeyDqMeaHvrkEQd7gQbaaJzQ09Rmq84fQG88yE6Q+ExtI4dRua55uMCq2vz+Z3TV/iBNebWOINAI/6tHX3say4JXd5W+XRLRbeYcULyJiDi/6h4QzmTcDqCDUXjuKA7Wtx4wPXDPjXngaYb0aMtBDjMy8GlB/PToZdKj141NnKr/eLHcQsPJEMy7Dj80sMt7izXybVFW7at2/eyS+nCXX0c1/rpM4iNG8e1b2q3Qdy5mYDlVCGEhxLPz2VMxOQONjQrx3+M9GoVePETYV6SizQukAR7tZUgGWKYZK+acyrSIQqSh8s3mvDP8JmFJsQcws9J4V+aD5UudJ5ViYZ2cRzRUvr+K4Qpsa0AvrtZHWMVHRCsIE1ETaextluxk7ym/F5ngsCYcdWRs2LnTGeH6nyIH+M+rsSp3UguYKGAq/swtwz9ZSI0f3azLqDNwRuPNaRGewy6U13DxAd/ISJZDmzrXMyUPkg5RwpNbVlaKLgMUGmgpMyxcp6LTulV+avqjPtsOn6EkmAFrzj7hc9+dOj64HNYmV5zY65JdsmkMhGQRFWF8+k4qjJnmDFO8QMBoKZ+Kn4LU8Lrf9EmrZl7lNk0Mekmj81pGddtfYgLUhCByX3yIjAS/Pg4WFMEuC/AcseEi0FD4OUSOJHqwEJwuqcXvIFrXONhi0avL6veCuTWgkOCfIDmL0Ioh+p44QlL0FtLo0HD1Gn6Tg==
    username: AgBO+tXP1gbjwPdwwtwxvsvFbAo8qYEsVpwtTNShUeQTaIzlybPh7eTysLva24jjDMBlo9okrqh/kRnhpvAwPjovecOuCLDT+UCQPSMo23WnHD0DLX5M0AmP0YH+Nwan+ZFhxn2BFZhVmZ66HDo7PfxLxnPx9QrIqjryAQDJ++s7zB9crUMJ6lHlRtcwDTb4K8KsFbjRGIE+yMvHW1dowzMclxw8g/sSOQK73s4HOtBTe5X9dHqtMT0f+R3H4iXmAmTv/9zwlT2jS5TIMjeNOJ6B2Foz8fTYY0x3vKrdReYC9LoeUgxF98qeLdCU8d6rLjfGwkoscTaqWBuh8WBNMAyL1fRNZ95ChXL1khP3iZ6yBUVhQjmVxDYlaETeRx5KuETlb5M8iwWwsVVfTrvE7qjklMSypNKZoM3UR/3szvdGwAgiaqF/qm7x6luYO78yEPaS9vXZWlFbnSY/pTl+MC47MK+PgQzYT8HZhHVYcOFF6HoyImYhQbA3ZG6wHwUm6XuOY8MOmuTCEAQn97YvwFNSX/sTmxZb46ynhttrwvkuBr862ep4wXKpm2DsEES/JvJ2Wz7+cI1sY6pK12Y/eUz7fJRedhi2t6knP1/AEI01LK70OMUHzLWnJ92oTVMC58/oU3bCzN73XBxbhYX6/dONwCu48kIbZRtteq+7SB01b724W8ylWRMYnubezkV0mjAz0fOATw==
  template:
    metadata:
      name: alfio-cnpg-secret
      namespace: cnd-ticketing-2027
    type: Opaque
