apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnd-analytics

resources:
  - cnd-france-scw-secret.yaml
  - umami-cnpg-secret.yaml
  - umami-secret.yaml
  - cnpg-cluster.yaml
  - cnpg-scheduled-backup.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
