---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: umami-secret
  namespace: cnd-analytics
spec:
  encryptedData:
    app-secret: AgBB/x7zqx8ilSpQIOzypPEaYbL/dgElhTgDAMUWY/prAaWPrIt//ZIegCVa71OPwzdoZqxkXe0Q+MLH12lcYwKpvpm1T/l+pLjRZ+v1VW6lIDOl29eS9cMB4VTHEFwB9DH16BKrDwEXiHFUIFXs6DrMW9pz0509t/t1sfCEpXI/+nhV8o6NM3/O8GPOujvkD3mkfHkiSD5b6jNJecsXi9u6LBzVLXwArFu9uMYKGOr3sm4rf5Liw52yLfWcfzPWO0TnYC1bM3LPTlcoU2B3/uvgKZUgjvVHPbiei7MXFpGKtyay8zdoTE/B2Vc3b9pw1S5sQddxRxY4Ut2Y51fhQOere7C/oA462qenBI5dnhPvaRk46+gwd7VK+n+aYpfe9HzGHP4M2oOVC4MD5/5tHhegcs49RSPNvz8pig2ny+yFPsbCGnn4QTn/S37Ply+9ShvpEYzvh9zn8BOkn+Txkbt+biNb9FhiSd4N2EsuKCZ8VymHyRUN3Yc8Ex1NXUjeX5ngtFhq/ITlymmLVGk2O40e5Kk3dXuWpeIZrZRX6M939ZU8B2ZfJy/mxQfdod33XDYEwD4kbbxzEXE+G4/9oJxd2knJMwNlYlFSGHa5nZe1H8VBRlxHmNsX47z+PKrOVbhhKkQgudxpv6UgAdW+JgYUOsfvDL4sbeI70CbZnfifaVxSHnHzIUqSANCVDOrC3AaPuYV2cRMsXZsjmmrt10yIjYY/yJ1qnh7KfRGeZvqOTtpn1b+eHU7O0qwK0Q==
  template:
    metadata:
      name: umami-secret
      namespace: cnd-analytics
