---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: umami-cnpg-secret
  namespace: cnd-analytics
spec:
  encryptedData:
    password: AgByd9StnPaZP+Cgpr92wXTXtSLVmrRcMhzPtjiCZ19+vWTxVFi+HFM6KlsSFTNoMVieev7TqYUubMdya1H0SaioExKv49MaQLXC814c6Vb33jzuUJpvs/Df2rDQeFlSjwqlOgtETL3ZUjgDUToqmKqJNYS9x+oAEqpr3t2HPBuo67y1iRpEY92RJy9I6PBKBKFg2R8Rni5wAfIfdVbgvTixW5tIL5CgBgpaC+7eBSsrFYSWHAtvIQu3/zvjVeShBqBD8SQKA8fQj6WH3h4sLj2xeoDACgNd+RNAxhIPe0zGA/5DML34S0Ka7F6BQdj7sdAOQpBIAtm/oECA4iIP4k24WV/SkJ7lHMI86bQcVVEOJh5VeyBV3LbEjTelRd1EVktRtZtPAVqEDHla0x+huJjoAq1gSF26sI5bhZUFUFpDjkpKSbmHJWlPfNcmtuop1K2P2ZYIe0AI7q+WrJtYHH+PXO/16o8hrWvG3ROblo4E2eOJFnGib9VUA7wXJdlNP3LVty3N4n+PbD/tbUrV5Tf9EAlh0AWiIok5h87f3miUjKimW+cMeq8uhxLWyKf5lv0gEdQ8wAaLjSlpvBz2WzEvEnaKR9tiCueo+bojdy9H4GYB6YlpmCmeLXpaGrYnVQkJswSUJKwgbJhDQSQ29b0oXhq+tdpV2m8Hb4F8l+AsO8swgmr5+Yl09+lL2fBYnVNVjQfbFpgmUYO3qJeNggHqb8ubmm5/gWL8sJY/TZryU9F4wTbf3BkHmzJC1o3OcppSIKt0TtoGrKTUiLWonKQO
    username: AgBbp6w+tWeaPpISyf1auCvOjNhR1dq1y7WUqgi0VDHXhGCv2RqymJix09zkZ7NfDKJH+FIuqyYUTmL1nqyDFKvpFiYtMPGgOgh1DYRJ/znUCT6flLduPhdJsW4xd9shoMt1tBmy2lrgyIenz8L6RAj2qVrpbUYGVO88kp+/UNGHnyEtu/FKwESO2OVKdzMwIxyiZ6CNf2+vJg/BjR7TKUm/h4CKA+FuHXQvNnUQ3tdRk1jOzUlKFlYB6XGqV6JTmlmPPM4taSKg126Ifxiue4fr3U9ckWt1gEvKpcRjEqGNHwqI1Y+QhtIT0qlppw/lKYc9PGxuOuI0bYLkamHarRBNiBBLS0d2vrc2RgmjJfpMGKw6z5EP1zUqspzOwOuE0orX8Ap/x2xBnhkCP60xC+U4BDMdhafTnxK34Lx+CjeTxtk0A941GipgAJ+UNpMq+2/Hbvo+337aw/BATKoerymsdxcjuVfffFsqN/Jq4Hu+SInxsob3dzAXtMRPT2bV4Y07jMZncXtnyONR0xp3Z0Wo+YI1SXhc4rwfZxzwlWaEWnSe04ayhFovc8ANrDyZO0aLDWac+gSlUDZaUJ3GsfN+VIoXE7V5fgdsDXpJDPOAl/9roG4HlVg8h3TfPmDym6jYRz7K8OztVCk78f8Y17r0u0rL3m0dMzcpfPDnfk5o6yaHiho3SM13I3P7LqQeN7PafuXfSQ==
  template:
    metadata:
      name: umami-cnpg-secret
      namespace: cnd-analytics
    type: kubernetes.io/basic-auth
