apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnd-callforpapers
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./callforpapers
  dependsOn:
    - name: cnd-operators
  sourceRef:
    kind: GitRepository
    name: customer
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: cnpg-pretalx
      namespace: cnd-callforpapers
    - apiVersion: apps/v1
      kind: StatefulSet
      name: pretalx
      namespace: cnd-callforpapers
