apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnd-communication
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./communication
  dependsOn:
    - name: cnd-operators
  sourceRef:
    kind: GitRepository
    name: customer
  healthChecks:
    - apiVersion: installation.mattermost.com/v1beta1
      kind: Mattermost
      name: cnd-france
      namespace: cnd-communication
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: cnpg-mattermost
      namespace: cnd-communication
