apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnd-matrix
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./matrix
  dependsOn:
    - name: cnd-operators
    - name: cnd-flux-sources
  sourceRef:
    kind: GitRepository
    name: customer
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: cnpg-synapse
      namespace: cnd-matrix
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: cnpg-mas
      namespace: cnd-matrix
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: matrix-stack
      namespace: cnd-matrix
