apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnd-ticketing
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./ticketing
  dependsOn:
    - name: cnd-operators
  sourceRef:
    kind: GitRepository
    name: customer
