---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brevo-smtp
  namespace: cnd-photos
spec:
  encryptedData:
    password: AgBbH9/hq8JVCm3cgQi1OkNYZwuAs1sQyiYfU1Tk8+u1g9UyLC5bfhYVJOjvJr5qBv8eVix/LGqm7oYTPopD1cR3+N+6JfBu+gv/yLlb/ZVKO4X8jQb7XlNBuKejyQ10XWCwDNnSieVfpBR0gAWU5xu75mHBjB8095/2u0FH+VFWXnqql+agQ8KtndWgPc04q66u2HYonmlPS/Eo8VwW5Q9bazI4vBwRVZPJ1vQTIHDH1At2lffdiBIYPUIBblNNLiG5lWpUY/89QrrEHvsfkJH2yOTiONGsi3ash2LwaHCgOu5N9shvvaQnPDdCPYgm5H6lbp9pJ1ylxNyOQC9p4EPyShnPf7Jh9x+Qog6fyDxvY/iIYCmrPt7L12C6W6qtYSY6LU9e/7hFemPGgdEGaVeQrhPf4DsoD3t0+U4wEXoQiMjEbaTsqoEyrB6Ma/Pvi6k1Z9/znCEfS7n6EdNVeFujn4w51vPnOY19RBnUTvmoIWbf2q3Rf95J5KewmouTeJ2h4wJ63gysCUcZiBB8qQ5C8MmfhJFcslf+HpI1TFWbBQiGubdyV1EfyAopfJqzNG99t1Rcz1RtykL7VRb8QZLzVp2HmFsQ7hviYgjljvveyuA1I9l33fF7Ngch+UK9NeayRcHtmYIhZ+QwX6/QWG42zBU7or+sgOMfaKUk1Ztujj2XP3jA1P5A4j8cTGg1IXxwPdSkCCUJm29xubLEpMBT
  template:
    metadata:
      name: brevo-smtp
      namespace: cnd-photos
