---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brevo-smtp
  namespace: cnd-photos
spec:
  encryptedData:
    password: AgCPeW5dAbLlp57rUX2699YHTxlU22J6y2rlRbtlEOCc/2x2DwyEvAeWkNZuoh+En/QaLxpKSGlXbbtTKJsMhMcVqvSnzpXV/Visd8wfC3p7bhEhEUtdL/vKRaZd+a2DI3gjZP+gVHKUBU53lM+g1vjoilVsziwmqkPxnfLF/EvgEKoTgWmJmGog8iKXWfHeMbT9kdeL2O+j8vrcemoY6i9wubnJhYilW+U8fmnvX+PqJy6W8x6vhmFJdAfGVdJrgjJwq6CUCrr8PZ92+dcfFZw3BASAjDfAAI47ApB+b6uUVsD6lOivSkId0kRNFOGB0au2a0ZLu4hDalvpQfW0e5agbBvvukfw4n/dD6Ky6H5bseXEnlzNap8ei6PUTwIibM0bdQV6Pzqo1YO8pOo27Rr09qeRVKEu0KRV40xOT7Je1F8Z7G1YeMMGVOgiY7gh08Kqil0jnEV0/72kD2pQoDCjLEc8pxZaTaS3WDu7XJjQPgDAJXAjINUsOHTr6/2lnPNBKYb2XrIKae4bjgmz41360yRaiAtqzJ0v184FOxtmlqUAIo57vS6auVcTaviWNO/qfBCVfW3xmNQgjJbtfGLKg04uK/gkSZIm3tPpczUpAxJVl6F1jD1Y5cGgH3d9BkjUEz9VaHAWDw0GjR51+60OgFGVFfQfqVYCS2Ji/fH+wvlt5zJsbznQdG0EgZq8IPRl/RyrWLE=
  template:
    metadata:
      name: brevo-smtp
      namespace: cnd-photos
