---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ente-cnpg-secret
  namespace: cnd-photos
spec:
  encryptedData:
    password: AgCYxdrRO2M7q/vaTHIFzgSt+ZcJ6xzrIaR9hueVUUu6vFkHF1FtdQyHY1TJgVgSM9aNjJQ2Rfljl3ngDI89ydtmvm5xFYfcRQFH1iR0Ub0x+x8pruA/mDQbiWc+6QxzaRuW7QABx74eHq+XHMN1SL/CgSiza+ViWN016J3c7H54SV9X7dmkKp1UNwaTHH0W6LYSBrBUwtOiXBiZkGKISnjchUiyByhak14jNuyQ+TGhp9EkJLKxGqV3uX3lSDBQprapKAZWc9tbm/AHAShmwdt1RM1GtgRr2j5zLUMj8+Q5IkASoe2Sylbvk07oorZrPjtoKFv2CXygZOPsRHdU8jQXDMuXDlb1EZMQ9XR/frkVw1W3rk6BIK0UytUOkfVND7zzlxBYH5PY9nERUZdxOAuzxyelU9sLoV1C0Nt21OZ0HRb30s/KFoL4YUptiEr8UY7z5q0QAL5EbE769rAkQXW26MXdk1UbL+PA5JO+6VGpbafDOY0ZzclSDSPsGio6B1taqZ35iEjttlHYMFWpwOInx3aDOalFdugtseBRv8GHv1LzFeW+MqbNb7CPPJ2QpAgjsYlgS0cZ8dC+kwIOuszW0XVoQNd4WvYGdKI699TosR2eS7qRDSS9rOna+gVq/+OyHwJazjIyGcUXEcZ1B5F8l4E0pj6knfDgXke9hwqkO6yCLctg1PD/VIa6xKG7PcvLTwWhuynokYf0NSNuENmygu9p4NHUGrcurkga4+t10w==
    username: AgDU2jxcKky8hfw7FHv6WUKR0nsR+QI36hyWnFtFt3BpJXb+xNcCkS6AFZttleG1V9WAcvi2W6UVYonjKLpYKNhmhPfJaf2yCtdQkRzAKdewn8GtrBkY4jPa70UZvfhaNAn/1WgNuu9WmwmUpPG4ocBgtKXnzhzdZGfTl93B9/G5O6L3wJgDKlL2buRUFwvD5sqgg0jtZOEVtsymsg/L5+Ngyv9iJ4w3TB3tzswg3JePafEeeUhoSCPJrJEWxGsshyZglOQstErwcIJXB8f79OiZVMTMSKtmsulGBifQ5FsHQEcFE873yX7nFcJzhR7F1xckihhEXcRF0zluqDAUCrrM9pH9HNpo5ZCHc1PPgLAPzTOyvSE8uVsmyygS20NWPpKiZyHboJHzZfC/KZsK+j7oXrHsnjIyBjJuKtND3EMA2/0Vvet3+qSPztCEgkK9cU7btLn1MGfoMoJleZs+LoJn7smVNvrs8j4r5w5GLXpwvo/IT4liqdjnyL73yyWMoMK+lIEVL6yWxzm7liVHTCfab8M16BDKV0Xn2ZyGaOWoyNAHIV20oQrkn4VcFEcQZIA2qQNoRJSnY+WwRDFwHQ1QOI8E7qWPEYi55whfOhu0IOMizrboO/R3wZ5KnpF62GXplGGF3KYI3sdl5n44KxzSZn/rA9BUwbKG7pqbz760koO1Cn3nS3+yb5sPN9BNI4inI3My
  template:
    metadata:
      creationTimestamp: null
      name: ente-cnpg-secret
      namespace: cnd-photos
    type: kubernetes.io/basic-auth
