apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnd-photos

resources:
  - cnpg-cluster.yaml
  - cnpg-scheduled-backup.yaml
  - cnpg-secret.yaml
  - cnd-france-scw-secret.yaml
  - brevo-smtp-secret.yaml
  - museum-secret.yaml
  - museum-config.yaml
  - museum.yaml
  - web-albums.yaml
  - web-accounts.yaml
