apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnd-operators
spec:
  releaseName: cloudnative-pg
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: cnd-operators
      version: "0.24.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    monitoring:
      podMonitorEnabled: true
    resources:
      limits:
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 100Mi
