---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alfio-cnpg-secret
spec:
  encryptedData:
    password: AgBpxra6AM7a571sruLydOX49/aiRUZX9Y6orw6KJ3V3+9Gapd9R/8JX45Mp8RG7KLzpHslzQvyxBJgmMj7LBKCufAOmfv05tbdLri4c066th2eU9Bqnv2YJsh3OWQugZF2tUg9OLv3eOw3uR93uJgKj0EkG88akCtJ3B2NVLI0w5HiNrXOR+jBDywr1AZAcTS7TsiT2MPSgva07r39ndfAwK7UKYpHgtAVUGRTiIYHDp7N3jIXCeI1iCHZDLyS8+xBmH9zIj1YB+p5PiKgHTPii4OQv143KucFDNiz+T6tI3ADnnWssCxdOcwinal+JinYbmO1+7m3CxHRg5pqLGJaOfqJp+NSbG/4wxQFN8jlNzB+ZSVuIlom7FF1Cv5GwR+/kCpElBdR+0+8owlle6wv9TgJWJAJ8AgcxJg6NWobF+67abUFbpZuP4M5Um9ao+PlTmjr+SC0JIlpET9E+uNRNtB/AjT9l29taBjTYxz21rlJ/GXyRdE4pZqSjmBrsOGGtFhsdbFqC5Yxo6JyOgLlM+3+2g2HmZ36GCpv+eKlka9ip0cOCk0fhNRQxgzpSO8MIbQaoU9XCXDxpNavpcgPmvqe6ATEv9Bugdf+c4CWpCHlCkeGEEFMaVWBo0WnNCqVCNdIWf9010FDfrPvsR1MQmLvSP5MzU2eScoSighbAZ+onOne1ekppBC4GsA1FwtyHTZJ6UM9RbMKklikeQdLbq4p4g6FLMg==
    username: AgCnTri6H+t7f+f7FincLcPqAjGJ9W1wW9xiRK6DDe8qLBXAqkQA/VnLU2Qt+rDg4XIZuJp2P6pTJl4feJgTJfO2kJMBiDPTODE1czfwFRbu0ttY9pzlYfkMeJK6SR1fNQo64cxy0xtsCgVD3gWC26YlAi4q9dBkNeHmfJdBQXv/s5CzrndV2y5IJokiHDMRVHY9bfFK0/gz9g51MAENtjC+eX6+/2wMuGBtJNdWOZbFNCRcCnYiBxgNces7Scg6Z8ZlFoowBVnl5+xi+kQJstJhCdHIpKiYSavkSsK4lzkrTL81oYgUxUe45jwDSgv4DskbSuZBjV0wJ3DctQmdMML9bzcVBKYq2/GfLjF3zxFWUSE2TU1wY8qkKEHr34rgHQKKL7/26HNPN/z7CHvkdiizJW2q2hI+Q6q+PBn94W3Z+kTmZZ0tMBK/JsAmT9KkOAsYjIC9FI8JG9nc95XsAsG3cHcnsIiPnIw4GIm8jn6MCiJsd6kby2JYYPeHzjRFaQFB3seA4Q5WfMaZjlsDu77eDnTUHtj77mqRTXzJqTIxZptjTd0OIe8Euo8UN8ptijLZ+a9/ov/1Lo7bPGQdy+E53kp+U0XHmk0UsAZqKlk5iNdD9BFagW3lHiziIB4XFZqxx/181s/JVyU2jwzHDH/vKvMWWwQ8mr4Rgia4K+KsAki6bvj0OAvXbSg3Egwxm9Sk31dM7w==
  template:
    metadata:
      creationTimestamp: null
      name: alfio-cnpg-secret
      namespace: cnd-ticketing
