apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: alfio
  name: alfio
spec:
  ingressClassName: public
  rules:
    - host: tickets.cloudnativedays.fr
      http:
        paths:
          - backend:
              service:
                name: alfio
                port:
                  name: http
            path: /*
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - tickets.cloudnativedays.fr
      secretName: alfio-tls
