---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plane-godmode-auth
  namespace: cnd-project
spec:
  encryptedData:
    auth: AgAewTteyV4v0ZEVhYoRnuW+mu4mvhIkrlBYl4Mvqq52QUTJVYDZIcsnNfqwV0wt0HLY4t2ETtdtdPqsWP4cT1FoKMgAYkSasiTyliDglunXuqiJqEl9apN4afIUGVsKoXea2ua6f4VJdBK7miiCBvv+WKganQyCa/IBJzaNJKeYpVCsoSeKbyFviNDsoKiVNEl+jXNpLqcgvuVr5TXn+5IeizADNO5/xmCc+V0Nve3IswxmSQMxRhnPjRvA7ShIcS2n3E359jgUj48Rf02wgGzZCnLCCLOOyhHGXYfUwgMUAyf9da5ayRCQbP2L+IinT+DuJtLhKhga2VZI0D+mZs/FSaahJRlRR/EZAdtDvXygPFhkg66bEbpFTOmSl0DBDcoxXIWzy408DKkV8F7g8WSf0BQ7dtc6aR12aNfaj93X1O+JuDd9iubSOiWmp+LtqZrgZNwaYpNvp9InSYsAOcgu+fjLvxJWHERwRSUossTGfSMhhIgPKgJcLIlU7F3iee/txvc4n8hDAKji7DZ5XRIAViDsajb4/c3pUOBk6a4mcnBkJLgSK17ohqYjwJ1We2LxsT1A5YfC0pBTeW0tIvKYnYd5SZVIgHyujReKlJqjnzgilUjyn8mH/UIWWbdkCZG4+B4H2O8Fuy1r5bGFHuNoCvxalV6D89l1RSdhwfg9soSvmWn1onKAmMK/IX86kXJiTFaucZXqyoJkJ2Yln2duzUJ2PnuVztMDSAi1vmdY35ibmDgNoS/reg==
  template:
    metadata:
      name: plane-godmode-auth
      namespace: cnd-project
