---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plane-live-secret
  namespace: cnd-project
spec:
  encryptedData:
    LIVE_SERVER_SECRET_KEY: AgB5TlzdGMgule+tFGd6h6igXcANyfzVaHcJEIZ98zYFyBkxtphM8627Sv226xrsV/28xbuvkbd+udAIePbAzCVjre47vAujMv1UOVsvhmmuitM4aAn4KDZQVqRW96Gol5NCBnUjm36ENOxq/CyIjiphCrBvV6IbIgiCOSPDNVQCq37mITHdk/MOlU9TM99p3lBpSToJQL3hDmeOxkNYoB9SsKuo9WLN1lunBO1FETm/B7aeq/3TMjYqtXlaxm1LdGfGR8VDOjuUKR9lh0wbPsV1TKqHbgPg7CKZboeDuyhxqUBAaBD2SAz5cyLc4cwSYal/b0wupsQ7Bfw//lHSVomtG+HfLit29Wtv/Sngq/HrTuHgvfWylMdO6HAF1bl6a9EgHqoEB4pBptfNIPcdnld974oI5HBNrZdmD2VYTiL/wLk3dwmrxueDLA3nnjk8G+w//wUVbVNQszStQcDGwbDzhsWk7+b6ccI/geQ4uyxSeLH2RRXEM5cnT1h9sdKN53I8k8vrmEG30KX9XeiN4CU+MstKjNHU5M7+GHguBdPx1LHhzdCOSTeURQUz4jDyeMLoEmYX19bYIEikZ76WafpbSvmGgk7D7RQ5bDV8fLVgLoaxpZh3ChhMJAhP6xupfV4MOCNGKgdd2vSK4xYkYcFJxO8FS7zpfUizHAs+YGPMpFhoVD0or640TtCYc2RKtgA0yanlrwBNkDu3iag208etOTIoxpjzN8yzY+XkFKatKpLUt0aVNFP4Kegu4QoYHFwS3fDnI4tse1VsXFn42UeM
    REDIS_URL: AgCPT2v1Msyrs4bh+sNggb9GG8OFBUJkqhzuyjD7/ucxVY2suTIR3QlLd6XnVjB3wFVLfK92qZehN5QQFnW3qSHVT9fxhb2pyylxLGgsoXUrPJZqDOFtdBaguq78oY4vgB6FbWUV7fWwZ2c3tWw/DeCYuCblH01FidVHBhWsjl+h88F+wOqSCb5VFFXdqUFcd+46GzUz+ak38B6ciD0VqfuG6k74zKww7d2WXSMM/sEreG1Y8tTCrbo7opHUN9MNMdZ1PYro4AqnvHCttMVBYQcYOBEzFLsfQnJUeXNl4QPSHewwjQiBU7EVDqFiLVGVcfxBggNzd4a4CgSVehc7BoHzLbSmOA+HMxwRi5uhWl2EwKJ6MX5uPbqQ/vWtstufvjhibHWt+HR/tJCjXhxd4cRIZfg6cV7M/qYHZ2GdianxV5c7Qo8n8xwb+UIeSXT+VPzSbj2asTYZJCE8Ao72NiJXS2YLG8+pRcXz4UHOPAjzEygDB1gAqG+3VNfyQq71jtNHzqJOREmibxS4WCsbFPuCUoK9E51zNLX7yMME0KXmVWrgHepFAN0FWlhyrWau0ltidx7s3+nNJb5Pc5vbLiLujrVnq/XhBfJaW/Z7+YKxRBeHfNcg7KW2PdM7GY3G0OwnSBW9OwxPtMpnM9ia0d5+Ov4wT3YyvbyL5SjwXkM1VcM5I4N9F5q/pdt8ruAML8m0KkXO9aDH82sxtqGwqWfOq7W7VBcxVLW1WjI9FjT2VQWF9t3A2d7RcSKGDK6znc7vsv0gXRR7
  template:
    metadata:
      name: plane-live-secret
      namespace: cnd-project
