---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plane-rabbitmq-secret
  namespace: cnd-project
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCrDzWHc+Zp7tBSjSgRTGg8zRmC7j6yqKrZqy5zumIZ0dqe8xcDHL1dXQ4/FkJxxneqrRlxT+2K6ZcSN57zBNiYSkzAhetgB6EL95+yLD/UFTf1IBlmgZmVum81TMNqkqkAqIxVkN1PqNPzJft0dix0MaURSSQu4OyR7kWuTD5Us5uZ9YsdV20EAuZ1l6A2b5RRM04oZoKw0sEYfmDnrQHtG11/UiJ4tyizvjlaKfI7tEnyxtwlBcqdmkvGwmeX8vegcAVak+Zjz9pmwu/GqK26lYtVUlVVSA48TmpREBiylP0TEKyDmNqsKRIn6/o0CQ2IX3IHBrj746mZ3RHutrPn2bEMgzBLzRmzvtZ/aSSgFNyCxp7NDuQ+PYYmFsX3CNNmICCek/4Ly3bYemW6ghihlZlFbXbskndAgQbEGKWTXpkkn/0Z2WpjN/3tqRlVcKO2d0YvTuwhHz6kZ/ohzX+MolGsLeeXS7Mqa9MfsciQEDvQUsDG3ZXXgm7F7RT3LYEk02Du2CICGclrOHe2NCmPTooZWr9oaf8tFbSAkYEn+JC1Giw+8QFE60G5496R3ymgo65TOsND2oNrZ8DCQNfk45wNDH0U93XOYf8F03v52B4gZ+Fv/ZCHrbzGN8HoCH3lDKDLUGwnOdbgT6HSNIPPHeBRC8HpCKyUKezdm5xkshX3J/nSHDlzGpUcrPxMdBtEjREB5SQ/t87khZprrhl9N3aeBhUsTh/Lk+2EFSDLB1YSr9FE1dzxHxX61iK9Lb77mtnxfgsFi4fkAW8m++uI
    RABBITMQ_DEFAULT_USER: AgAAquZ2ouGMWk/Z2JiWkWljl97Xy28xTHE0yZM+drIggThNFKLzbNbMks1R2eCuIeoa/3T7/uhgfRwmc8r83pawh94XbXS8L69cPT5ZjI88VSuwhMBwYmPF1NVS+Sf+Ke3UEOVStja+QmtpbTMtRIT0A+IsxpS31lBGA9uLQ70Vv7d1I0P0oq21+A5qh3CriCrefZqhxmCMrn5JXRWPA3vcRodX5+0QBY8itfQL0KaJofg+Q6Guv5j3rzGGeX9D0EKjGry6v9MjErxjb/vdY5uuTjL3rqDIu3qwB5uF6wgexRUjkMH7a0oVQbSDKB9Ip+eSIKeb/MUUF/5+KRBUtCvmzmOcxAlPVT4Cd3moV54stLyEDi3QRsqnchHCrCbJsH9cSqGOqTdad1sqaj0+MvVrgBFKFlD3Sygjj9QD7yB/qcutCXugM61TYYGDl9aOVh1QKKpibAqrip5JOeHFQvGNKfuwRYly/122GOvCauT0H95oNIu74l/nAx5NLRxAJt33LQAcmrw/bPs84akq4sO4OOMGxUuqgNUVQYMBRxP2YlU9nyCbBTikAw1/+Q+x4Qe7KJJlChjVjaEoQhK2w2rO+PRXIAy4rz/6R9j7BBpB6AnVtm1qqXJ4UJsacCekAfhPlG0Odqs9EPIBvXmAajhUJCEyR9OmbuqkGi82CvzpcSyv480PDsxP7v4naSDMiXQRnpwITg==
  template:
    metadata:
      name: plane-rabbitmq-secret
      namespace: cnd-project
