---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plane-cnpg-secret
  namespace: cnd-project
spec:
  encryptedData:
    password: AgA83jpXzsJSajXsx4BjLuXe9PQaewYNf8cR8xLpfWJVgUYxuQiXfQPtkdPmAHCzIyBfs2uyOmrHzEV9Mt8AY/o+uXtpzy1FKYx5yhlEH9kqW0R0MoQ8lyImP3pd2Lpeu5EOpXAsr+kzywb36kaGBMvg2FX5fEZr6O3SdsLnNwipqdW0gdyGViU3lesjCW2ObkrPofVXntzS6+Qudx2hhdtVJG6wfLFsxY0SVMMadjg+GtrG8fkrDen7hrx2wN5xYgle1o1jKPXl1zghBDnZ7z+o85zL9Qt/+q+PibrghpvkFHJ0IHVmT6jy3JhjhXb7Qdr6UFBbFFJyjKao46r64QcySvX5lI8Y0wDjG6P45JUb2Ztlv9GK5/5IhvRY1AxTGM8D0t37HDCMu5k0nXEnrXYB4dnMnQUGX7LrSX8sBbRubTJfhz4frAkTsYM81oQ9tdBoVLN0YJpvV/GYsB3gI9JSmAYxLC2NNdWihv3Qaw3TW0fGDwU4GFWmNqYBWQTd0oLp3/UQFD+aWbl2DsKzsO2zvvSGB7Vgk/2xTIqIl7jfPJyoxY3KEzCOPQQb+gcHvW3SxTO1yHr4LzLmo74IWz1LQ5XQt+2yVdOEa9V6VMnHYy5hIWEOBbJ95YZvqF7UtZiV6o3kICDcyQBj7hLng/YDxKqkCHGKBm9OiHD80asWFrKbMZ5xprvXDrZpqgcVAye5slLQ0eBDZxAgL0Vqd3Q0j+S0jnvG+SMH74KMEEkKeRS93aV3USjCWbYlKbIgYAsPiWv+fgU9ourhVI49KlxJ
    username: AgC+sEZwjzj+fZI06aAeuOMzzed7oIuiDLXr9jiJFMb4cq+1E2HIsNDmapN1kx/VOYjaHlfBVtNmvR6AAAD7MfdY6EtoaAjs1T50/XkbMwt+oKtBjRbd2VYWVLPqBzgZMobQ9oW8VMbb32mZbmhOyZeszeDx6T0kmzTir61WyV/4JZzUDjvZYTN2Xk+FOBAVPvrpE3ZjIPNPoVyCJXgNJv+ST9Byeqp3IqVewzRG4JWuaeiGn1TYnVNt57Cdu/UbnAz9oSA6/liZyBVNErZbjOKUJ5EoDt9SYs4BFgmOFnoWFeURuysvwmM959dbV24vIj+YfZCozTIqz4OX1dol3Xn+DhkJ4WCNJGrWiuMgr9cbA41pyzXyoojyQILbdms+YVWFZA9RkuBIwoiPa2gOfbhEJPVORZEZzmejx4EX5uVDDbRj5vftQDCJdsUyJKNioHojoH1MDiQwxfOg9iJOoBZXwJrN3a+o30NItmeP7w5J0vAqolYostyGSfIT14VC2mW8PP5S0Hci3dfTq1D15azoP+b3+7L1YDYmcvc7ZAOP1Hl5tPCY0Dhu6FF90v0zeDxpY7zi7SilMKm2PTm4zM1Pg0Qa7PI023o06vwz+Ao4vxoTmoZI0J+HveVfMNb0I9XPXB/NgrGXAKhbJtPbhuPGBASXWLyXijrkhq0JUzDHbjBGErWhQC6QqGzH716/Yf2R3cWX5w==
  template:
    metadata:
      name: plane-cnpg-secret
      namespace: cnd-project
    type: kubernetes.io/basic-auth
