apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: baserow
spec:
  releaseName: baserow
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: baserow
      sourceRef:
        kind: HelmRepository
        name: christianhuth
      version: "7.0.14"
  interval: 10m0s
  timeout: 8m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: "baserow"

    frontend:
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 300m
          memory: 512Mi

      ingress:
        enabled: true
        className: "public"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/proxy-body-size: "100M"
          nginx.ingress.kubernetes.io/client-body-buffer-size: "100M"
        hostname: br.cloudnativedays.fr
        tls:
          - secretName: "baserow-tls"
            hosts:
              - br.cloudnativedays.fr

    backend:
      asgi:
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi

      celery:
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi

      config:
        airtableImportSoftTimeLimit: "1800"
        aws:
          bucketName: "cloudnativedaysfr"
          existingSecret: "cnd-france-scw-secret"
          s3EndpointUrl: "https://s3.fr-par.scw.cloud"
          s3RegionName: "fr-par"
        batchRowsSizeLimit: "400"
        celery:
          amountOfWorkers: "2"
        email:
          existingSecret: "brevo-smtp"
          fromEmail: "baserow@cloudnativedays.fr"
          smtp: "true"
          smtpHost: "smtp-relay.brevo.com"
          smtpPort: "587"
          smtpUser: "8f026a001@smtp-brevo.com"
          smtpUseTls: "true"
        existingSecret: "baserow-jwt"

      persistence:
        enabled: false

      wsgi:
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi

      ingress:
        enabled: true
        className: "public"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/proxy-body-size: "100M"
          nginx.ingress.kubernetes.io/client-body-buffer-size: "100M"
        hostname: br-backend.cloudnativedays.fr
        tls:
          - secretName: "baserow-backend-tls"
            hosts:
              - br-backend.cloudnativedays.fr

    config:
      publicBackendUrl: "https://br-backend.cloudnativedays.fr"
      publicFrontendUrl: "https://br.cloudnativedays.fr"

    postgresql:
      enabled: false

    externalPostgresql:
      auth:
        database: baserow
        existingSecret: "baserow-cnpg-secret"
        userPasswordKey: "password"
      hostname: "cnpg-baserow-rw"

    redis:
      enabled: false

    externalRedis:
      auth:
        enabled: true
        existingSecret: "baserow-valkey"
        userPasswordKey: "password"
      hostname: "baserow-valkey-primary"
