---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shlink-cnpg-secret
  namespace: cnd-shortener
spec:
  encryptedData:
    password: AgCApB8Bv8RwJVNVAvWwxzf30Xky2NnfDmQT4hfIq0o7uzYqsXV6NsytSCkPvHjPb1nL1wAFQA1buxTyV/HVul7CHYgvaKCKLAj1JXxAbwB4UGFe5UXb+3s6AfkWRBA7O0O7fNi9G8DFPapbqZvWvoql+UtTOJzA+rMPUSV7g//PbAPD1XuxY81tuweNpbdD1dpEKgxPyNDchD0M6rhXR7aFmnko4Tw2sqf/NWihNe9w81f63jZ9H56tO+ejoS50zO+GzA7kCWwqJnK8+pgyDb8aAXi9KDZnk+K0UeSlrRyEe/9EkOrGVDwec2+QYklVXBNjzckAwZGRQ7PfceJqx0xunk+a+dpFf8IYbX/8y6WSn+aPx6BqiF1NYrdEe0EPX5vO+y/JTFW58EJ7Gp0CWtUFMdo78Y6DxaZtsDOuFm2boQlSuhFNgGqcJGs6crccIzEkV2LBXVpn8DVSUHqSGP3i+/AvgRPv04KhfbLkkKHyCIGjD1rDvASM8Prs648Zdb/0PhWCAXD16SIlrNIYOkGTNpoVwWlG0XElVeqU+FaeYxVfT4FhB0RZhevx9gyn1LGbohoewMuGIcidKaXnpgcrrJn9ScXRj2sLIHZjyDfKl44hg5/Nhi9VnTDCT/eD4L0cYbQY/jGFxpZe1XE+JXfpHTbO/P6Fp4/B6gIhpDd4ctn9swSdDktjIKId7ePLEqAtMO/9tFHdSMicOnJtmjBE2BUhywmQuIVAIGTwtGpgSUpQhWa8SXik1S8fnEWUNAkUNz6636aG6IB2voZEq2IB
    username: AgBpkW61k5a68BpO0xswke7BvvSJ9htE7XT1vIl/lLXbznSO03O9JjN+928cSeYnkdKEHm9PuH2+GgoLhZS+2ewQZItegipdAOUssnFJr34O7CNHIt1f5n717wd0xsoUa+a6DijhUjQS7SWrh6vFCMEAGP6FeSpBi1Si4Hts8IDWufqTb+pBfLHvXodnsjrQgkuHjQYAhiyeQXG3UqcIVdNu9GPrvMLCmsP0H0cCKF2N0WQUQapjSdm0/cW2Q9/u2wP64oqOIZqinWGl40tIz+Omcspjp2H8C6x1eSaCRUrWR6NupmuGJJyUgYmufaY5XNKmN+H3Qy8ckU5npQCxojHYjxQZql9oQQQ+kwJIcRmfq6gu0NUOqEs2B9eN2FYCIoje+h1YgpR4oAjMwfyuEh8G3DTnJZtxOvKFZnzt4poJ/6sWUJZYrQ5poatjYzXQFgY9yFVIDtuOzcwB4hdazVXw/3v9UDvbVAABGlrjHmMoKa0afDz5/Jh78zVhROF4swFw9eqxHex+BJDuipk6ZHnBMrgDDo9GS5/MtLT1NeBtbt4RQ7/S5HBJ08cHf75WZBk0ZjIfaI0NeR8OjwywmbfeR/Q2PTFcjLi0nR8YsggT0XAHRQ7/y/qzrYRNR9OCLT3U3Jtm4U9Od0H99myto7E3dynz+/ZbFguYoiVc1i//d8WorGzg+Bk8ZoOZ1Ec27sy0fdFY4dY=
  template:
    metadata:
      name: shlink-cnpg-secret
      namespace: cnd-shortener
    type: kubernetes.io/basic-auth
