---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shlink-secret
  namespace: cnd-shortener
spec:
  encryptedData:
    initial-api-key: AgB1lQ6+zJwElwi8LHEir6NuFitVvEv8FnAGvmXN9XJixhmT3xTnLv4oDYSOu7XZTWSBaa9ALmDYolGrkwRBlkMOLhljAaGmNEVyYCG/J31ETdJ08Kvwv3DYiqkT3jSbzltVHbJAi/ww/naOX9YuR5tNb/aqe6DNiL5i8yJaI2JveL7kCJN1b5R7Sx+Glk93LgDq1+lX6mY6/JeJjxyge9fES2LcNNxi4X5JH/sgl/lsxZ9q64COHBnMmrZfEu4UudMsGdfDsfabxYpEp54goX++ttFGITWSmuh/RR2MwKWFEPnoptUwlF0TiEX1X3CJ+9A8606ITM3QEwWMxsXbCHYKb7BuV+Rd8Kv9wWcWVkPUYqOR8qEk6DmoD3aA+1V0CxLxWfmk5YRkQhPuq20DtmltcpqlWZsKY+dBKJnR6jSrP8OeQEAbBaWjVzGRFUAa3PTB3j0qUxQeqYLPEu/I2eYpRtnXP8EYXLfOpAzTkCm76gx2mxRnTYxAf6QEKp7WW4tQk58adpa74hoyFD8trjufzSrf8F/Mgfye4caVNH/LxWiV41r6RhnZIfDfSIn+9NdcOoQ7Xs1F2EAmE9VY9oRAbt9HYM8msg51SH1yPIkxwHSGcZyhHnvupuI9uYNaLAiiaLlzBOP6GHV8+viL/J1B3XdeaFsJV5WtpTCEr+T9b2JGzXiWMGSG+IaHGRlJBYL6HkE31WkMuHg12Gq5jvfJOyWNqw+OkIHBi5KUyoE63JiRikg=
  template:
    metadata:
      name: shlink-secret
      namespace: cnd-shortener
