---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shlink-admin-auth
  namespace: cnd-shortener
spec:
  encryptedData:
    auth: AgB1ywEy1Hn3MFQnw5D6MpmPQ1Vl70UdYC/3dvqPEXJ1vaOjvKA+Di8tvEQnN/kFLug01aygX8YyAYe9/wxammHMT/yBMj1G3SjFIzabCPPfOYEV7Lc2hMcjhXW6T9USODYn/n5hcuW2XLXgbzE+xvUPyTvwGWrmffl6St6Cmb4XOJfMKZX0kt9z2FHKNalhTxQ+N8m7LkIbf5fSnfk4p7GxnAKXKijbABMMmX2TnvacouOJC8u6dcRLpFazLfH7rZn5G6/WWl3/cK2oDEKgyrJR0Jm+XlrwB88vOOjz828N95ot0+EfPORQwFSm6Rxcs/JnDmZk7m18NM4OBbQh0KDT8aO+Vj0DFmoDGwxF4kqvPWv58aqzNJj1UnSo4Rb8T7HFjuf1UwEKQvyt7w4IImZ/RzFHkMjyZHampt3mQHkVXPZE6mBrzwNP5Xt2i0kWuiuC6YTVHGK0+hnNYL2iq5QVl2BBnSHUiBNIHSFD9wfgiZAMq7MrWPFWNUHOaXI6zCrcB4N+L3Jj0GnZq+jILsZhqpCvwpUNdnP8nEtDkrPTBcPhcCj4ZQmYEk31U4QfBmxMYmInL7C5xunDHWiZ0gXpOUjPTW38bsByGhRWnHOua6cOx8NJLarcBZeVr0EL7E7qJvo8VOVYX4M7Vynl5h2kdfUBrtaRS0RFTCkR7Le5j3BaOdAzkc+OfnXJcxJEiSbwNwdXLJhLyWkLB7vIZB4XQvwm9VwaKvdDpHyimneOh4uKsKCqk2Pypg==
  template:
    metadata:
      name: shlink-admin-auth
      namespace: cnd-shortener
