apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-synapse
spec:
  description: "Synapse CNPG"
  instances: 2
  bootstrap:
    initdb:
      database: synapse
      owner: synapse
      secret:
        name: synapse-cnpg-secret

  superuserSecret:
    name: synapse-cnpg-secret

  storage:
    storageClass: node-local-retain
    size: 10Gi

  backup:
    barmanObjectStore:
      destinationPath: "s3://cloudnativedaysfr/cnpg/synapse"
      endpointURL: "https://s3.fr-par.scw.cloud"
      s3Credentials:
        accessKeyId:
          name: cnd-france-scw-secret
          key: accesskey
        secretAccessKey:
          name: cnd-france-scw-secret
          key: secretkey
        region:
          name: cnd-france-scw-secret
          key: region
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "90d"

  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
    podMonitorMetricRelabelings:
      - action: replace
        sourceLabels:
          - cluster
        targetLabel: cnpg_cluster
      - action: labeldrop
        regex: cluster

  resources:
    requests:
      memory: "768Mi"
      cpu: 200m
    limits:
      memory: "768Mi"
