apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnd-communication
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./communication
  dependsOn:
    - name: cnd-flux-sources
  sourceRef:
    kind: GitRepository
    name: customer
