apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnd-flux-sources
  namespace: flux-system
spec:
  prune: true
  interval: 1m0s
  path: ./flux/sources
  dependsOn:
    - name: cnd-namespaces
  sourceRef:
    kind: GitRepository
    name: customer
