apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnd-namespaces
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./namespaces
  sourceRef:
    kind: GitRepository
    name: customer
