apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mattermost-operator
  namespace: cnd-operators
spec:
  releaseName: mattermost-operator
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: mattermost-operator
      sourceRef:
        kind: HelmRepository
        name: mattermost
        namespace: cnd-operators
      version: "1.0.3"
  interval: 10m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
  values: {}
