apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: cnd-france
spec:
  version: 10.8.1
  # Disable cluster mode - not needed with session affinity for 2 replicas
  # Cluster mode requires gossip port 8074 which is not exposed by the operator
  mattermostEnv:
  - name: MM_CLUSTERSETTINGS_ENABLE
    value: "false"
  ingress:
    enabled: true
    host: mm.cloudnativedays.fr
    ingressClass: public
    tlsSecret: "mattermost-tls"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      # WebSocket timeouts - Mattermost requires 3600s (1 hour)
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      # WebSocket support
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
      # Session affinity for websocket stability with multiple replicas
      nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
      # Proxy buffer settings for large headers (prevents "upstream sent too big header")
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
  database:
    external:
      secret: mattermost-cnpg-secret
  fileStore:
    external:
      url: storage.googleapis.com
      bucket: cloudnativedaysfr
      secret: cnd-france-gcs-secret
  scheduling:
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
      limits:
        memory: 300Mi
