apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: cnd-france
spec:
  version: 10.8.1
  size: "3000users"
  ingress:
    enabled: true
    host: mm.cloudnativedays.fr
    ingressClass: public
    tlsSecret: "mattermost-tls"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  database:
    external:
      secret: mattermost-cnpg-secret
  fileStore:
    external:
      url: storage.googleapis.com
      bucket: cloudnativedaysfr
      secret: cnd-france-gcs-secret
  scheduling:
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
      limits:
        memory: 300Mi
