apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: cnd-france
spec:
  version: 10.8.1
  size: "3000users"
  ingress:
    enabled: true
    host: mm.cloudnativedays.fr
    ingressClass: public
    tlsSecret: "mattermost-tls"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/server-snippets: |
        location ~ /api/v[0-9]+/(users/)?websocket$ {
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $http_host;
          proxy_read_timeout 3600s;
          proxy_send_timeout 3600s;
        }
  database:
    external:
      secret: mattermost-cnpg-secret
  fileStore:
    external:
      url: storage.googleapis.com
      bucket: cloudnativedaysfr
      secret: cnd-france-gcs-secret
  scheduling:
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
      limits:
        memory: 300Mi
