apiVersion: v1
kind: ConfigMap
metadata:
  name: pretalx-config
data:
  pretalx.cfg: |
    # This is an example pretalx configuration file.
    # Documentation: https://docs.pretalx.org/administrator/configure.html

    [filesystem]
    data = /data
    static = /public/static

    [site]
    debug = False
    url = https://cfp.cloudnativedays.fr

    [database]
    backend = postgresql
    name = pretalx
    host = cnpg-pretalx-rw
    port = 5432

    [redis]
    # location = "" # Defined through env vars
    session = true

    [locale]
    language_code = fr
    time_zone = Europe/Paris

    [mail]
    from = admin@cloudnativefr.org
    host = smtp-relay.brevo.com
    port = 587
    # user = "" # Defined through env vars
    # password = "" # Defined through env vars
    tls = False
    ssl = True
