apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pretalx-valkey
spec:
  releaseName: pretalx-valkey
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: valkey
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "3.0.22"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    auth:
      existingSecret: "pretalx-valkey"
      existingSecretPasswordKey: "password"
      usePasswordFiles: false

    architecture: "standalone"

    primary:
      resourcesPreset: "nano"
      persistence:
        size: 2Gi
        storageClass: "node-local-retain"

    replica:
      replicaCount: 1
      resourcesPreset: "nano"

      persistence:
        size: 1Gi
        storageClass: "node-local-retain"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
