apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pretalx
spec:
  ingressClassName: public
  rules:
    - host: cfp.cloudnativedays.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pretalx
                port:
                  number: 80
  tls:
    - hosts:
        - cfp.cloudnativedays.fr
      secretName: pretalx-tls
