apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pretalx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10M"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: public
  rules:
    - host: cfp.cloudnativedays.fr
      http:
        paths:
          - backend:
              service:
                name: pretalx
                port:
                  name: http-static
            path: /media
            pathType: Prefix
          - backend:
              service:
                name: pretalx
                port:
                  name: http-static
            path: /static
            pathType: Prefix
          - backend:
              service:
                name: pretalx
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - cfp.cloudnativedays.fr
      secretName: pretalx-tls
