apiVersion: v1
kind: Service
metadata:
  name: pretalx
  namespace: cnd-callforpapers
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: http-static
      port: 81
      protocol: TCP
      targetPort: 8081
  selector:
    app: pretalx
