apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pretalx
spec:
  serviceName: pretalx
  replicas: 1
  selector:
    matchLabels:
      app: pretalx
  template:
    metadata:
      labels:
        app: pretalx
    spec:
      containers:
        - name: pretalx
          image: pretalx/standalone:v2025.1.0
          ports:
            - containerPort: 8080
          env:
            - name: PRETALX_FILESYSTEM_MEDIA
              value: /public/media
            - name: PRETALX_FILESYSTEM_STATIC
              value: /public/static
            - name: GUNICORN_BIND_ADDR
              value: 0.0.0.0:8080
            - name: PRETALX_DB_USER
              valueFrom:
                secretKeyRef:
                  name: pretalx-cnpg-secret
                  key: username
            - name: PRETALX_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pretalx-cnpg-secret
                  key: password
            - name: PRETALX_REDIS
              valueFrom:
                secretKeyRef:
                  name: pretalx-valkey
                  key: redis-url
            - name: PRETALX_CELERY_BROKER
              valueFrom:
                secretKeyRef:
                  name: pretalx-valkey
                  key: celery-broker-url
            - name: PRETALX_CELERY_BACKEND
              valueFrom:
                secretKeyRef:
                  name: pretalx-valkey
                  key: celery-backend-url
            - name: PRETALX_MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: brevo-smtp
                  key: login
            - name: PRETALX_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brevo-smtp
                  key: master-password
          livenessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Host
                  value: cfp.cloudnativedays.fr
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Host
                  value: cfp.cloudnativedays.fr
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: pretalx-data
              mountPath: /data
            - name: pretalx-public
              mountPath: /public
            - name: pretalx-config
              mountPath: /etc/pretalx/pretalx.cfg
              subPath: pretalx.cfg
          resources:
            requests:
              memory: 1.6Gi
              cpu: 300m
            limits:
              memory: 1.6Gi
        - name: pretalx-worker
          image: pretalx/standalone:v2025.1.0
          command:
            ["celery", "-A", "pretalx.celery_app", "worker", "-l", "info"]
          resources:
            requests:
              memory: 350Mi
              cpu: 100m
            limits:
              memory: 350Mi
          env:
            - name: PRETALX_FILESYSTEM_MEDIA
              value: /public/media
            - name: PRETALX_FILESYSTEM_STATIC
              value: /public/static
            - name: PRETALX_DB_USER
              valueFrom:
                secretKeyRef:
                  name: pretalx-cnpg-secret
                  key: username
            - name: PRETALX_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pretalx-cnpg-secret
                  key: password
          volumeMounts:
            - name: pretalx-data
              mountPath: /data
            - name: pretalx-public
              mountPath: /public
            - name: pretalx-config
              mountPath: /etc/pretalx/pretalx.cfg
              subPath: pretalx.cfg
      volumes:
        - name: pretalx-config
          secret:
            secretName: pretalx-config
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
  volumeClaimTemplates:
    - metadata:
        name: pretalx-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "node-local-retain"
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: pretalx-public
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "node-local-retain"
        resources:
          requests:
            storage: 2Gi
