---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pretalx-valkey
  namespace: cnd-callforpapers
spec:
  encryptedData:
    password: AgA/ivwLP1yYJTU+8u3MUU5NZ+caYF2yYLb0NxnFu9O4ckesVwLLLzfj7YgtQsznDDSqsAVofJGkHH5i8L7NqRz0XDqfSdIKhNxmpouzopdft4YGv8LZSLvp3wCN8aPdzINMemdn0XZgUfzDh42uHMuPHy3cOCJDIxmexAHe6fwhI63dw0kn8Y7ur9GFG6juG8J6Q3nyJyvbg8LrKFZkSbmJvo6vWpupliVIWabKSRcHUjEC6aP3GCzM15WUe2tLriNiQK5vmZMk+jdLABN43k8LUdUqMAQoYy+Db2gxmT25PCQ9ahh7UW4DXPPCzVN39uSPl/62pvx+12nuoEeF4jivuv1cK3HmrW6Dtwkr3VR70y7AAVOMuRR32Xf3SkmlyshY9BaWhtDaaVbqvg/iKZk2jYtFGVGBns0K3afHUEJm+2MKdYVv2lcGZITkjKa+9+WFrMeM6C44SAxU1Dvx/v7VUfY9KNpBDwMTGpvi5rdmYiNh4TYztXqvMGiW/pEho+kc3efktiq8mxEc3sZtp2OMFTTz7ZWTzV0YnvZR2kjdGzouXbZNr7SVs/guQBHQzCNnv3WN0V9NeMZ8/z5aRRByagbKLaQxBg2wVEG2rhiZNsbObMIuKTaGvbnVAuMNJlv72yjIPbEmdUDKsAWjJoNEDf/Ss08A1ydcHgqnkY2Z3Uxl6tB8IGclLVjogglMIhUbhZGqaFWDPee1GiCfUn7ZJ4wlVhbre5c=
  template:
    metadata:
      creationTimestamp: null
      name: pretalx-valkey
      namespace: cnd-callforpapers
