---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: website-staging-auth
  namespace: cnd-website-staging
spec:
  encryptedData:
    auth: AgA4O9Ud9a57QHJRX6MyOslnAnj0vhE8msp5MV0uSFwRWlT9ntdm97LCuFxhOjf9AL61z8kJkFz+FAW2wcDpag5B8ykHVDxdlRboIAsZvlZA3whPYW69AD9wdiQ2cXTCm7fSMScOmvAdjb1TlA7lkNk2yLadKy49au/7VWLJDdRdQlk0dcRTGazq2SfKfiMSYFG+YnU7wtFgz6yJqnmPhR6IKITj/+QDaOrKJP2iAhwpWAgWBbDLPG+jc1fsLuKi4t0KqSXDbHUJMyTob2YG1nA95H9beNVP6KcDpZ5/k6bPP4hfDkKHuX3Rr6BoDh4HS7Cv6L1O84TMZ8dltFHKJKaY0ZBBkyk46x7XfU5ncxmbz+ThAK594fG9r1bnSaP1CgsC65+5Vy1ctK9v/vST4tEXgi894oxBELfXcBoHA1xAPmQFIta1gYF5lx6nV8+JCYXDtdbqX6998p/iaN96LlCnrJ5mP0OkPHn/9GfohFxdWueY+y4RyCaYRMomnBY2/i69jMBQ/ZkWvU2iXp3K9LYZVV0MIUkFJW3DG5JndVXwesCD1lAcJpIJkdt34Rz4T5Y9u0SXvqMPGFWQFep8fIZOyaGnaj1XLMTY33gfFwLJrbbGHv4jWIh5UzWgFAYznw7prOVP1/InTELqWaFM1c1VNKQT+w+nNjeFF8wzTcumqJR7Dx2KDkLeHYuw2xeK24QVpo+ppMGINy4imdCEsInV+kU4WhpBA5ymoWh9V8TZBY/69fNNUWacrPyM4FZJfE+h0PiflkxZ6UHuhIrWJHkdhzY=
  template:
    metadata:
      name: website-staging-auth
      namespace: cnd-website-staging
