apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix-stack
spec:
  releaseName: matrix-stack
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: matrix-stack
      sourceRef:
        kind: HelmRepository
        name: ess-helm
        namespace: flux-system
      version: "26.2.2"
  interval: 10m0s
  timeout: 8m
  install:
    remediation:
      retries: 3
  values:
    serverName: matrix.cloudnativedays.fr

    ingress:
      className: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

    synapse:
      ingress:
        host: matrix.cloudnativedays.fr
        tlsSecret: matrix-synapse-tls
      media:
        storage:
          storageClassName: node-local-retain
      postgres:
        host: cnpg-synapse-rw.cnd-communication.svc
        port: 5432
        user: synapse
        password:
          secret: synapse-cnpg-secret
          secretKey: password
        database: synapse
        sslMode: prefer

    matrixAuthenticationService:
      ingress:
        host: auth-matrix.cloudnativedays.fr
        tlsSecret: matrix-mas-tls
      postgres:
        host: cnpg-mas-rw.cnd-communication.svc
        port: 5432
        user: mas
        password:
          secret: mas-cnpg-secret
          secretKey: password
        database: mas
        sslMode: prefer

    elementWeb:
      ingress:
        host: chat.cloudnativedays.fr
        tlsSecret: matrix-element-tls

    elementAdmin:
      enabled: false

    matrixRTC:
      ingress:
        host: mrtc.cloudnativedays.fr
        tlsSecret: matrix-mrtc-tls
