---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: website-basic-auth
  namespace: cnd-website
spec:
  encryptedData:
    auth: AgCoI+VHVFSNVaNaR0HgaC7euYe9iysP0kNOzXjndnGNyeUaNnUQOsC67nyrFvBNtUZKNBCryDCAzJmahUrUcpNGS2yaMgTddkMNHlS2pWwg7odbapAud/MtvWJ858pj9vPbg+11kStI+MXHVMtDdkaxEZlE1df6k01JPqjz2jLU+2Eh5KnyGrR3mC1Kiz3ZYcmTcjdXieLzuQwjIborMwR9kikgYvfXn4AXaN/zn8x3sCkOroksMXHK6kMA+lnGNG0Yi4eWdOCIxWN4IAv4H5bJw4k0rDFN063uQQGnXOb8a03/0ibYcC2b028TAK75FVx/xVOWzB12oT1S5mpwd9hQvNI/iu5MOtXbbZn+Cs1STVPzjQJp15KOmJvPgB/TcGTZeNnY15u/lx0kqwo/glhwwDifLAePshYCUEPoF4OR5bs2+p3rdD8ADlQIr3TnWi7P00+lMwmSSz0jeIn5NKpPFQZdFgrYmn0Y5gpkiQmQ9D8CSKrSckkQYHztdWQ/QgH9Ljes/RZ80Na8WvJSbzdaHdzcyniJjxwPUboZmhFENm4OAbaLYEixbU6nlteUlRo0kaAfuSEJsIIFIF//70lzPAigR29pr82byRWvNmZodmePFbDbrK5tpBxGWoEfw+bAkNaVuOv0rslp69/Nvzuf2V+HprVl6SMlAc3YrHl3nBua3YJ9YAtk/rp1bX0btGjvtlqcOO53jKb5SVLVYYSl6JHidomwqW38hKBAggX2M1aBuX05PNT6gZGwM0EPS7gEfeMVGj5Ejg4Y0SEq1CPtKg==
  template:
    metadata:
      name: website-basic-auth
      namespace: cnd-website
