---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openproject-cnpg-secret
  namespace: cnd-project
spec:
  encryptedData:
    password: AgCttB5PQ3gZvcgBL7REIGy90XYpOxADDx3j4cRJ12jvBpbqa8MUi45fRD/FokEf0pTFGKg4b/UF0T7U8YwNi4qh98hg4Sd8/tsDqPcyKrB5bOces6eohdlSH6c5J6+u8cgHvAA+KJwImqLMf8fFW9TvAoUVhDow94sDAKEcRlzYPU2uPMyVInOXPufXixe0lICtoVwICWcQuRmHnCgG2JmI5l16fjcaUgfgPPYJkWTKLuYqH/n6smTl4KAHiEyXAc8WBqKLY81UL8g4GhUPVoG7Kho9jBFKO/IOzZBDid/5AX8O8QLB2e/5L7Kk1QeTub8izt+MdKBqYWhrQcnrw7nkCCzfVZC+iJrGyb3oUf7AIacd4+ZN/sxzKUXUlYHu7qRj4FUw07TAZYPA0cPNVF0l+KfK20y1txCpvTlVQa3XIuPtQhVX9xCpPZdvpqqXP6s0/CEYYRrhWl3VfvvG7wp3Yrf0e5/VhR3dorLxEX+drQq/A72W5OHS134S6GFlITqaU2+mctJq7aMFL8h3Br0H8iYkRgA+tTXTrmOoXKSTVmJey0Lb3vgtXIWQdHAcT0zs9dFiAZ0lXEencrNo9uCfRnm82/nlDgM8VsFXqy6PycIsgGb69V9t4P8VwcLgWefHk9QzD9mbDzM+dOY8z8vKaX15ib5NRe/3wIYm1NKfQoBl/Kt3E8HKlhSfohKtxxcGFImiU/TOkPTg1u60UqVOUfud2d5qag==
    username: AgAXaUtSyshi/3Waf80aBkCt0zJc4R9mDshbMEBJL+HefJQyqf6OKbVu/dKqOBJFenVLlFQk4lLVjS8dexBDRqpNA2+CSSNTQQd7MPfU4eRrV31A39YtDPkaa2geC+mDCn3H1B1L9SB1u7l47bijN2dD55ln4eBMCXWSrjT8qAV52vsUqjH9mIy6g7nHEJRkAzDFOFc1NlYwIMdD8TJSpoSKuCoLeMUMoP6MXKtadIkM/xDbdKPaWW5GtEX2uSEIpvKzS1XimOenWvSFXzjrNHBI6awQQB892DxbaxCRnkb77XnkgpFZSl+QspxTW8UwAocqnJ5DSruleZL6Vva4y+x1E4KB4cNUhZJWHmBkUdsMjNkXhb/kqvDhrmTe4/hvBm5/DmhPoh+mZ9kb/8Kj9q/M32dYEBFzrBXxYUUrNmzw1sQXaEWM+bTGPt15uZimU/c/BfXOjqfMUGR3gdNCkoQHpSrnlu/E9dmpZDiIeIqG23A8W3ujxakoT8gxn4iOzLLqqzAsReRwc7eScbFgvRu3FacLxFxjEPTwJ3I4mLgIZj6kL0QbpdjMV5IAXilVmpGgh7AKhAwyIcef3kVlUPg2YNElA5OHhP6HWnchWb0l9MarHyLRjOoSgS08NhXZ3QQIJqrZ9d6pxg7bHZpxMAIKSLoOTABLmB1gmUUc7HKwWVV9PsNCDvyDEBWszCs564BG3g6wPL2FjSsDiA==
  template:
    metadata:
      name: openproject-cnpg-secret
      namespace: cnd-project
