name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:

  kubernetes-validation:
    name: Kubernetes validation ☸
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Validate Kubernetes manifests
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          verb: call
          module: github.com/Smana/daggerverse/kubeconform@kubeconform/v0.1.5
          args: validate --manifests "." --exclude ".github/*" --kustomize --catalog
